### ISSUE TITLE
Awaiting instructor approval - on edge.edx.org

### ISSUE THREAD

**Issue by lukasc-ubc** [mitodl/edx-sga#137]
Hello,
I successfully used SGA on edx.org in my course (UBCx Phot1x), however, I cannot get it working in my present course on edge.edx.org (UBC ELEC413).  It says "Awaiting instructor approval"; see screenshot.

I have the "Instructor" tab at the top, and I am part of the "Staff" group, and the "Admin" group.  I can't see any other settings that specifically label me as an instructor.  The course team management section under Instructor appears the same in both edge.edx.org as well as edx.org.

Has anyone else been successful at running SGA on edge.edx.org?

Thank you
Lukas

![image](https://cloud.githubusercontent.com/assets/15843200/12214621/df413b1a-b650-11e5-8107-518d86280abb.png)

**Comment by lukasc-ubc** [comment]
It seems like this issue is resolved.  I don't know what changed, but now the Enter grade has been replaced with Approve and it works.

**Comment by pdpinch** [comment]
Instructors (aka admins) must approve grades before they can be finalized. Staff can only enter grades. 

If you are finding the behavior to be different from what is described in https://github.com/mitodl/edx-sga#staff-grading please let us know and re-open this issue.

**Comment by lukasc-ubc** [comment]
I'm having the same problem again in my other course, ELEC463.

I was originally only a member of the admin team.  I just changed it to both the "Staff" group, and the "Admin" group.  But no luck.  It says "Awaiting instructor approval" just like above.

Fix -- I logged out, and logged back in, and that seemed to fix it.

**Comment by tony-h** [comment]
This problem still persists. My user is listed as both "admin" and "staff" in a course, but the grade status read "Awaiting instructor approval".

@lukasc-ubc thanks for the tip to log out and log back in! Logging out and then back in allowed me to "approve" the grade.
